# Generated by Django 6.1 on 2026-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_url', models.URLField()),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('applied_date', models.DateField()),
            ],
        ),
    ]
